# action.yml
name: Wait for a http json status field
icon: activity
color: green
authors: yao, guilbep
description: "Wait for http json response status field to match finished or error for a URL with timeout"
inputs:
  url:
    description: URL to poll
    required: true
  APP_NAME:
    description: APP_NAME
    required: true
  API_CD_TOKEN:
    description: API_CD_TOKEN
    required: true
  JOB_ID:
    description: JOB_ID
    required: true
  timeout:
    description: "Timeout before giving up in seconds"
    required: false
    default: 30000
  interval:
    description: "Interval between polling in seconds"
    required: false
    default: 200
outputs:
  result:
    description: outputs the response from the call
runs:
  using: "composite"
  steps:
    - id: main
      run: |
        echo "${GITHUB_ACTION_PATH}"
        echo "${{ github.action_path }}"
        timeout ${{inputs.timeout }} ${GITHUB_ACTION_PATH}/main.sh \
        --url="${{ inputs.url }}" \
        --APP_NAME="${{ inputs.APP_NAME }}" \
        --API_CD_TOKEN="${{ inputs.API_CD_TOKEN }}" \
        --JOB_ID="${{ inputs.JOB_ID }}" \
        --interval="${{ inputs.interval }}"\
      shell: bash